version: "3.0"

services:
  db:
    platform: linux/arm64
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306

  backend:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./frontend:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd react-project && yarn start" #コンテナを立ち上げたときに自動的にbuildする
    ports:
      - "3000:3000"
 
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf